<a href="https://colab.research.google.com/github/muskankapoor97/ai-learning-journey/blob/main/week2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
python_list = [1,2,3,4,5]
numpy_array = np.array([1,2,3,4,5])
print(python_list)
print(numpy_array)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [11]:
print(python_list * 2)
print(numpy_array * 2)
print (numpy_array>3)
print(python_list+numpy_array)


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
[False False False  True  True]
[ 2  4  6  8 10]


In [13]:
a = np.array([1, 2, 3, 4, 5])
mask = a > 3
print(mask)
print(a[mask])

[False False False  True  True]
[4 5]


In [16]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(b.shape)

(5,)
(2, 3)


In [18]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])

print(b.shape)
print(b[0])      # first row
print(b[1, 2])   # row 1, column 2
print(b[:, 1])   # all rows, column 1

(2, 3)
[1 2 3]
6
[2 5]


In [28]:
def get_average_np(nums):
  arr = np.array(nums)
  return arr.mean()


def normalize_np(nums):
  arr = np.array(nums)
  if arr.min() == arr.max():
    return arr
  return((arr-arr.min())/(arr.max()-arr.min()))

def standardize_np(nums):
  arr = np.array(nums)
  if arr.std() == 0:
    return arr
  return (arr-arr.mean())/arr.std()


print(get_average_np([1,2,3,4,5]))
print(normalize_np([1,2,3,4,5]))
print(standardize_np([1,2,3,4,5]))



3.0
[0.   0.25 0.5  0.75 1.  ]
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [41]:
Q = np.array([[1,0,1],
              [0,1,0],
              [1,1,0],
              [0,0,1]], dtype = float)
K = Q.copy()
V = Q.copy()

d_k = K.shape[1]
scores = Q@K.T
scaled = scores/np.sqrt(d_k)
def softmax(x):
    expt = np.exp(x)
    return expt / expt.sum(axis=1, keepdims=True)

weights = softmax(scaled)
output = weights@V
print("Q shape:", Q.shape)
print("scores shape:", scores.shape)
print(scores)
print("scaled shape:", scaled.shape)
print(scaled)
print("weights shape:", weights.shape)
print(weights)
print("output shape:", output.shape)
print(output)
print("Q-shape:", Q.shape)
print("d_k:", d_k)

Q shape: (4, 3)
scores shape: (4, 4)
[[2. 0. 1. 1.]
 [0. 1. 1. 0.]
 [1. 1. 2. 0.]
 [1. 0. 0. 1.]]
scaled shape: (4, 4)
[[1.15470054 0.         0.57735027 0.57735027]
 [0.         0.57735027 0.57735027 0.        ]
 [0.57735027 0.57735027 1.15470054 0.        ]
 [0.57735027 0.         0.         0.57735027]]
weights shape: (4, 4)
[[0.41018578 0.12927083 0.2302717  0.2302717 ]
 [0.17977126 0.32022874 0.32022874 0.17977126]
 [0.2302717  0.2302717  0.41018578 0.12927083]
 [0.32022874 0.17977126 0.17977126 0.32022874]]
output shape: (4, 3)
[[0.64045748 0.35954252 0.64045748]
 [0.5        0.64045748 0.35954252]
 [0.64045748 0.64045748 0.35954252]
 [0.5        0.35954252 0.64045748]]
Q-shape: (4, 3)
d_k: 3


In [42]:
arr = np.array([1,2,3,4,5])
expt= np.exp(arr)
final_arr = expt/expt.sum()
print(final_arr)
print(final_arr.sum())

[0.01165623 0.03168492 0.08612854 0.23412166 0.63640865]
1.0


In [46]:
X = np.array([[1, 0, 1],
              [0, 1, 0],
              [1, 1, 0],
              [0, 0, 1]], dtype=float)

W_Q = np.random.randn(3, 3)
W_K = np.random.randn(3, 3)
W_V = np.random.randn(3, 3)

Q = X @ W_Q
K = X @ W_K
V = X @ W_V
def attention(Q, K, V):
    d_k = K.shape[1]
    # step 1 - scores
    scores = Q@K.T
    # step 2 - scale
    scale = scores/ np.sqrt(d_k)
    # step 3 - softmax
    expt = np.exp(scale)
    weights = expt / expt.sum(axis=1, keepdims=True)
    # step 4 - multiply by V
    output = weights@V
    return output

print(attention(Q, K, V))


[[-0.46025847 -0.53675417  1.49625828]
 [-0.89812529 -0.11350909  1.45782066]
 [-0.93487024  0.04249063  1.543383  ]
 [-0.4624431  -0.6197815   1.4333241 ]]


In [45]:
print(np.random.rand(3, 3))
print("---")
print(np.random.randn(3, 3))

[[0.0233005  0.76042524 0.55167398]
 [0.11934918 0.12379584 0.71196957]
 [0.96557113 0.26191965 0.06307929]]
---
[[-0.70416521 -0.31013936 -1.05085088]
 [-0.59791864  0.22760313 -1.92040454]
 [-0.69933912 -0.88815759 -0.18954304]]
